// Generated by gencpp from file yhs_can_msgs/ctrl_fb.msg
// DO NOT EDIT!


#ifndef YHS_CAN_MSGS_MESSAGE_CTRL_FB_H
#define YHS_CAN_MSGS_MESSAGE_CTRL_FB_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace yhs_can_msgs
{
template <class ContainerAllocator>
struct ctrl_fb_
{
  typedef ctrl_fb_<ContainerAllocator> Type;

  ctrl_fb_()
    : header()
    , ctrl_fb_gear(0)
    , ctrl_fb_linear(0.0)
    , ctrl_fb_angular(0.0)
    , ctrl_fb_slipangle(0.0)  {
    }
  ctrl_fb_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ctrl_fb_gear(0)
    , ctrl_fb_linear(0.0)
    , ctrl_fb_angular(0.0)
    , ctrl_fb_slipangle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _ctrl_fb_gear_type;
  _ctrl_fb_gear_type ctrl_fb_gear;

   typedef float _ctrl_fb_linear_type;
  _ctrl_fb_linear_type ctrl_fb_linear;

   typedef float _ctrl_fb_angular_type;
  _ctrl_fb_angular_type ctrl_fb_angular;

   typedef float _ctrl_fb_slipangle_type;
  _ctrl_fb_slipangle_type ctrl_fb_slipangle;





  typedef boost::shared_ptr< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> const> ConstPtr;

}; // struct ctrl_fb_

typedef ::yhs_can_msgs::ctrl_fb_<std::allocator<void> > ctrl_fb;

typedef boost::shared_ptr< ::yhs_can_msgs::ctrl_fb > ctrl_fbPtr;
typedef boost::shared_ptr< ::yhs_can_msgs::ctrl_fb const> ctrl_fbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yhs_can_msgs::ctrl_fb_<ContainerAllocator1> & lhs, const ::yhs_can_msgs::ctrl_fb_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ctrl_fb_gear == rhs.ctrl_fb_gear &&
    lhs.ctrl_fb_linear == rhs.ctrl_fb_linear &&
    lhs.ctrl_fb_angular == rhs.ctrl_fb_angular &&
    lhs.ctrl_fb_slipangle == rhs.ctrl_fb_slipangle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yhs_can_msgs::ctrl_fb_<ContainerAllocator1> & lhs, const ::yhs_can_msgs::ctrl_fb_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yhs_can_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad19b49a2e6a5698ff08c7a9632728dc";
  }

  static const char* value(const ::yhs_can_msgs::ctrl_fb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad19b49a2e6a5698ULL;
  static const uint64_t static_value2 = 0xff08c7a9632728dcULL;
};

template<class ContainerAllocator>
struct DataType< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yhs_can_msgs/ctrl_fb";
  }

  static const char* value(const ::yhs_can_msgs::ctrl_fb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header   header\n"
"uint8    ctrl_fb_gear\n"
"float32  ctrl_fb_linear\n"
"float32  ctrl_fb_angular\n"
"float32  ctrl_fb_slipangle\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::yhs_can_msgs::ctrl_fb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ctrl_fb_gear);
      stream.next(m.ctrl_fb_linear);
      stream.next(m.ctrl_fb_angular);
      stream.next(m.ctrl_fb_slipangle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ctrl_fb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yhs_can_msgs::ctrl_fb_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ctrl_fb_gear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ctrl_fb_gear);
    s << indent << "ctrl_fb_linear: ";
    Printer<float>::stream(s, indent + "  ", v.ctrl_fb_linear);
    s << indent << "ctrl_fb_angular: ";
    Printer<float>::stream(s, indent + "  ", v.ctrl_fb_angular);
    s << indent << "ctrl_fb_slipangle: ";
    Printer<float>::stream(s, indent + "  ", v.ctrl_fb_slipangle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YHS_CAN_MSGS_MESSAGE_CTRL_FB_H
